version: '3.7'

services:
  fastapi:
    image: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./Backend:/Fems-Project/Backend